In [5]:
import numpy as np

In [8]:
a = np.array([1,2,3],dtype='int16')
print(a)

[1 2 3]


In [3]:
b= np.array([[9.0,8.0,7.0],[4.0,5.0,6.0]])
print(b)

[[9. 8. 7.]
 [4. 5. 6.]]


In [5]:
#Get dimension
b.ndim

2

In [6]:
#Get Shape
b.shape

(2, 3)

In [9]:
#Get Type
a.dtype

dtype('int16')

In [10]:
#Get Size - 16/8
a.itemsize

2

In [14]:
#Get total size - total number of elements
b.size 

6

# Changing specific elements/row/column

In [6]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [19]:
#Get a specific element [r,c]
a[1,-2]

13

In [20]:
#Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [21]:
#Get a specific column
a[:,2]

array([ 3, 10])

In [22]:
a[0,1:6:2]
#[startindex:endindex:step]

array([2, 4, 6])

In [7]:
a[0,1:-1:2]

array([2, 4, 6])

In [9]:
a[:,2]=5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 13 14]]


# 3d array

In [10]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [12]:
#Get specific eelement
b[0,1,1]
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [13]:
#replace
b[:,1,:]=[[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# # initializing different arrays

In [15]:
#all 0 maatrix
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
np.full((2,2),99,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)