In [4]:
import numpy as np

In [5]:
a = np.array([1,2,3],dtype='int16')
print(a)

[1 2 3]


In [3]:
b= np.array([[9.0,8.0,7.0],[4.0,5.0,6.0]])
print(b)

[[9. 8. 7.]
 [4. 5. 6.]]


In [5]:
#Get dimension
b.ndim

2

In [6]:
#Get Shape
b.shape

(2, 3)

In [9]:
#Get Type
a.dtype

dtype('int16')

In [10]:
#Get Size - 16/8
a.itemsize

2

In [14]:
#Get total size - total number of elements
b.size 

6

# Changing specific elements/row/column

In [7]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [19]:
#Get a specific element [r,c]
a[1,-2]

13

In [20]:
#Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [21]:
#Get a specific column
a[:,2]

array([ 3, 10])

In [22]:
a[0,1:6:2]
#[startindex:endindex:step]

array([2, 4, 6])

In [7]:
a[0,1:-1:2]

array([2, 4, 6])

In [9]:
a[:,2]=5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 13 14]]


# 3d array

In [10]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [12]:
#Get specific eelement
b[0,1,1]
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [13]:
#replace
b[:,1,:]=[[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# # initializing different arrays

In [15]:
#all 0 maatrix
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
np.full((2,2),99,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [8]:
#other number array //a or a.shape
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [11]:
#Random numbers
np.random.rand(4,2,3)

np.random.random_sample(a.shape)

array([[0.02620479, 0.09696637, 0.05471357, 0.60388699, 0.65965937,
        0.3806978 , 0.53748819],
       [0.50974588, 0.68475783, 0.52181404, 0.26672043, 0.66936825,
        0.00694164, 0.56441996]])

In [14]:
#integer   ---> 7 exclusive
np.random.randint(4,7,size=(3,3))

array([[4, 6, 5],
       [5, 6, 6],
       [6, 4, 5]])

In [15]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
#arr = np.array([1,2,3])   or
arr = np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [25]:
matrix=np.ones((5,5))
print(matrix)
z=np.zeros((3,3))
z[1,1] = 9
print(z)
matrix[1:4,1:4] =z
print(matrix)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Be Careful when copying arrays


In [32]:
a=np.array([1,2,3])
#b=a  #does not make the copy of the content
b=a.copy()
b[1]=100
print(a)

[1 2 3]


# Mathematics

In [34]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [35]:
a+2

array([3, 4, 5, 6])

In [36]:
a-2

array([-1,  0,  1,  2])

In [37]:
a*2

array([2, 4, 6, 8])

In [38]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [40]:
b=np.array([1,0,1,0])
b+a

array([2, 2, 4, 4])

In [41]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [42]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

# Linear Algebra

In [47]:
a=np.ones((2,3))
a
b=np.full((3,2),2)

np.matmul(a,b)  ##matrix multiplication

array([[6., 6.],
       [6., 6.]])

In [49]:
c=np.identity(3)
np.linalg.det(c) #### determinant |c|

1.0

# Statistics

In [52]:
stats = np.array([[1,2,3],[4,5,6]])
print(stats)

np.min(stats,axis=1)

[[1 2 3]
 [4 5 6]]


array([1, 4])

In [54]:
np.sum(stats,axis=0)

array([5, 7, 9])

# Reorganizing arrays


In [59]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

#after = before.reshape((8,1))
after = before.reshape((2,2,2))
after

[[1 2 3 4]
 [5 6 7 8]]


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [62]:
#vertically stacking array
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

# Miscelleneous 

In [64]:
### Load data from file
#filedata =np.genfromtxt('data.txt',delimiter=',')
#filedata.astype('int32')

# Advance indexing

In [65]:
#filedata[filedata > 50]

#np.any(filedata>50,axis=0)    axis=0 -> column wise

In [66]:
##index with a list
a =np.array([1,2,3,4,5,6])
a[[1,2,5]]

array([2, 3, 6])